name: Snail Mailers
favicon: null
layout_spectrum: 0.3882068
typography_spectrum: 0.6654136
title: Snail Mailers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3d7cb'
    - '#141608'
    - '#5d6e25'
    - '#ffff6d'
    - '#8f9e58'
  brandStrength: 0.5
  lightness: 0.5602037
  saturation: 0.32525
  rhythmicContrast: 0.75
purpose: []
